trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- task: ChocolateyToolInstaller@0
  inputs:
    force: true
    
- task: ChocolateyCommand@0
  inputs:
    command: 'pack'
    packOperation: 'single'
    packWorkingDirectory: '$(Build.Repository.LocalPath)/nodejs-lts'
    packNuspecFileName: 'nodejs-lts.nuspec'
    packVersion: '12.8.3'
    packOutputDirectory: '$(Build.ArtifactStagingDirectory)/nupkg'
  